.Dd 9/5/2025
.Dt clocksyncd 1
.Os Darwin
.Sh NAME
.Nm clocksyncd
.Nd clock management and interface for time synchronization related features such as the Precision Time Protocol and USB SSAM.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
executable is used for the management of various clock/timing sources and the interface between applications and those sources.
.Pp
.Nm
is launched automatically by launched as needed on demand and should not be launched manually.
.El
