.\""Copyright (c) 2023 Apple Inc. All Rights Reserved.
.Dd 2/20/2023
.Dt cloudtelemetryd 8
.Os macOS
.Sh NAME
.Nm cloudtelemetryd
.Nd "Cloud Telemetry Daemon"
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a launch daemon for executing handling system-wide telemetry events.
.Pp
There are no configuration options to
.Nm . Users should not run
.Nm
manually.
.
.Pp
