.Dd October 21, 2025
.Dt DEVICECONFIGURATIOND 8
.Os macOS
.Sh NAME
.Nm deviceconfigurationd
.Nd Device Configuration Daemon
.Sh DESCRIPTION
.Nm
persists effective configurations that conform to specifications authored by system components, and notifies interested parties about changes in those configurations.
