.Dd October 21, 2025
.Dt DEVICECONFIGURATIONAGENT 8
.Os macOS
.Sh NAME
.Nm DeviceConfigurationAgent
.Nd Device Configuration Agent
.Sh DESCRIPTION
.Nm
persists effective configurations that conform to specifications authored by user components, and notifies interested parties about changes in those configurations.
