.\"
.\" Copyright (c) 2006-2026 Apple Inc. All rights reserved.
.\"
.Dd January 1, 2026
.Dt imageplaygroundd 8
.Os "macOS"
.Sh NAME
.Nm imageplaygroundd
.Nd imageplaygroundd daemon
.Sh DESCRIPTION
.Nm imageplaygroundd
provides background generation and asset accumulation services for the Image Playground
application stack.
.Pp
This command is not intended to be invoked directly.
