.\"
.\" Copyright (c) 2006-2025 Apple Inc. All rights reserved.
.\"
.Dd January 1, 2025
.Dt postersyncd 8
.Os "macOS"
.Sh NAME
.Nm postersyncd
.Nd postersyncd daemon
.Sh DESCRIPTION
.Nm postersyncd
syncs posters and other visual representations of your contacts.
.Pp
This command is not intended to be invoked directly.
