.\" Copyright (c) 2026 Apple Inc. All rights reserved.
.Dd June 16, 2026
.Dt tvremoted 8
.Os "Mac OS X"
.Sh NAME
.Nm tvremoted
.Nd Apple TV Remote services daemon
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
manages discovery, connection, and communication
with Apple TV devices on the local network.
.Sh LOCATION
.Pa /usr/libexec/tvremoted
