.\" Copyright (c) 2026 Apple Inc. All rights reserved.
.Dd 29 Jan, 2025
.Dt ValidUpdater 8
.Os Darwin
.Sh NAME
.Nm ValidUpdater
.Nd Update the valid database for revocation.
.Sh DESCRIPTION
.Nm
is a system daemon that updates revocation database for
.Nm trustd
.Pp
.Nm ValidUpdater
is not intended to be invoked directly, but launchd though
.Nm launchd .
.Sh SEE ALSO
.Xr launchd 8
.Xr trustd 8
